### ISSUE TITLE
Build fails 

### ISSUE THREAD

**Issue by virajpadte** [startwithsierra/utils-legato-mqtt#1]
I am getting this build error: 

/home/mangoh/utils-legato-mqtt/mqtt.api:83:22: warning: Parameters with type 'handler' are deprecated.  Use the name of the handler instead: e.g. SessionStateHandler handler
/home/mangoh/utils-legato-mqtt/mqtt.api:106:12: warning: Parameters with type 'handler' are deprecated.  Use the name of the handler instead: e.g. IncomingMessageHandler handler

Do I need to do some upgrades?

**Comment by majdi** [comment]
Hi, what is the version o Legato you are using?

**Comment by virajpadte** [comment]
Hi @majdi I am using legato 17.07.1

**Comment by majdi** [comment]
Ok thanks @virajpadte, I'll take a look and give you the fix

**Comment by wedapashi** [comment]
@virajpadte 

I made following changes in mqtt.api file and it worked:
Changed Line #83 from 
`handler           SessionStateHandler`
to 
`SessionStateHandler handler`
And, changed line #106 from 
`handler IncomingMessageHandler`
to 
`IncomingMessageHandler handler`

**Comment by virajpadte** [comment]
Hi @majdi and @thibs0 
Thanks I made the suggested changes but now I can see another error:

_build_mqttService/wp85/staging/read-only/lib/libComponent_mqttComponent.so: undefined reference to `mqttMain_getClient'
collect2: error: ld returned 1 exit status

**Comment by ThomasOst** [comment]
Had the same error as above building the project in developer studio  and circumventeted it by simply  renaming "mqttService_getClient" to "mqttMain_getClient" in mqttService.c

**Comment by majdi** [comment]
You can check specific version of mqttService here: https://github.com/mangoh

Regards,
